### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by dineshrawat1459** [dbrent-amazon/amazon-advertising-api-php#1]
Hi
I am using your amazon advertising api , when i call this function 
$request = $client->getProfiles();
i am getting Authentication failed because maybe i am not getting profileId blank i dont know why its getting blank and how i get this you can check here https://dineshr.powermyanalytics.com/amazonapi/index.php

i have call these below function print the result you can easily understood
$client = new Client($config); 
print_r($client);	

$getProfiles = $client->getProfiles();
print_r($getProfiles);

$listCampaigns = $client->listCampaigns(array("stateFilter" => "enabled"));												
print_r($listCampaigns);

Could you please help you figure it out, i really appreciate it 

Thanks

**Comment by dbrent-amazon** [comment]
Hello,

Have you registered for access to the API? https://advertising.amazon.com/API

Brent

**Comment by dineshrawat1459** [comment]
yes and we were approved

**Comment by dbrent-amazon** [comment]
We handle integration issues outside of GitHub. Can you respond to the onboarding email with a good technical email address so that we can create a support account for you?

**Comment by dineshrawat1459** [comment]
Yes you can respond me in my email adresss
dinesh.rawat1459@gmail.com

Thanks

**Comment by dbrent-amazon** [comment]
I created a support account for you. Please use it to submit integration issues. You should be receiving an email soon.

**Comment by dineshrawat1459** [comment]
Ok thanks , I have submitted the query there
